services:
  hotel-recommender:
    build: .
    image: hotel-recommender:latest
    container_name: hotel-recommender
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
